# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The greekLit subnamespace for CTS URNs
tagline:          'A CTS URN subnamespace for ancient Greek literature'
description:      ''
baseurl: '/greekLit/'


author:
  name:           'Neel Smith'


paginate:         5


links:
  - title: Data archive on github
    url: https://github.com/chs-tg/greekLit
    external: true
